#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := hello-world

RELATIVE	:= /c

IDF_PATH	:= ${RELATIVE}/ti-software/bmptk/drivers/esp/esp-idf

include $(IDF_PATH)/make/project.mk